version: "3.9"

services:
  gas_electricity_meter_reader:
    container_name: gas_electricity_meter_reader
    # build: 
    #   context: .
    #   dockerfile: Dockerfile    
    image: ghcr.io/cbrown350/gas-elec-ha-sdr-reader:latest
    restart: unless-stopped
    network_mode: host # used when rtlmux can't bind to host on some platforms
    # ports:
      # - 2222:2222 # rtlmux
    environment:
      TZ: "America/Denver"
      MQTT_HOST: "${MQTT_HOST}"
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: "${MQTT_USER}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      LOG_LEVEL: "${LOG_LEVEL}"
      RTL_TCP: '/usr/bin/rtl_tcp -a 127.0.0.1 -p 1234'
      RTL_MUX: '/usr/local/bin/rtlmux -h 127.0.0.1 -p 1234 -l 2222'
      RTLAMR: '/usr/local/bin/rtlamr -server=127.0.0.1:2222 -msgtype=scm+,idm --format=json'
      WATCHED_METERS: |
        [
          {
            "type": "elec",
            "unit": "kWh",
            "unit_multiplier": 0.01,
            "id": "${ELEC_METER_ID}",
            "rtlsdr_id_name": "ERTSerialNumber",
            "rtlsdr_value_name": "LastConsumptionCount",
            "icon": "mdi:meter-electric",
            "device_class": "energy"
          },
          {
            "type": "gas",
            "unit": "m³",
            "unit_multiplier": 0.028316846592,
            "id": "${GAS_METER_ID}",
            "rtlsdr_id_name": "EndpointID",
            "rtlsdr_value_name": "Consumption",
            "icon": "mdi:meter-gas",
            "device_class": "gas"
          }
        ]
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
    devices:
      - /dev/bus/usb:/dev/bus/usb
    healthcheck:
      test: [ "CMD", "/app/healthcheck.sh" ] # make sure both rtlmux and rtl_tcp are running, adjust ports in this file if needed
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"