version: "3.9"
services:

  gas_electricity_meter_reader_workspace:
    container_name: gas_electricity_meter_reader_workspace
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile # development dockerfile
      # context: ..
      # dockerfile: Dockerfile # production dockerfile
    environment:
      - TZ=America/Denver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - /var/run/docker.sock:/var/run/docker.sock
      - ../data:/app/data
      - ..:/workspace:cached
    devices:
      - /dev/bus/usb
    command: /bin/sh -c "while sleep 1000; do :; done"  