version: "3.9"
services:

  gas_electricity_meter_reader_workspace:
    container_name: gas_electricity_meter_reader_workspace
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile # development dockerfile
      # context: ..
      # dockerfile: Dockerfile # production dockerfile
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
    devices:
      - /dev/bus/usb
    command: /bin/sh -c "while sleep 1000; do :; done"  