name: Build and Deploy

on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:
    branches:
    - 'master'            

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - 
        uses: actions/checkout@v4

      - 
        name: Setup Python to generate ChangeLog
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - 
        name: Install dependencies for pbr and run to generate ChangeLog
        run: |
          python -m pip install --upgrade pip setuptools wheel pbr
          python -m pip install -r requirements.txt
          python -m pip install .  
          
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/cbrown350/gas-elec-ha-sdr-reader
          flavor: latest=true
          tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
  
      - 
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - 
        name: Create Release
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
          name: ${{ github.ref }}
          tag: ${{ github.ref }}
          commit: ${{ github.sha }}
          bodyFile: ChangeLog
